### ISSUE TITLE
Unused dependencies in flake.nix?

### ISSUE THREAD

**Issue by Luk-ESC** [stannls/nixify#5]
See
https://github.com/stannls/nixify/blob/f7c93c8a4441db7fa8884ff9b4399c370ca3b875/flake.nix#L19

Not sure how this project requires openssl or alsa-lib (can't speak to pkg-config).
Maybe they can be removed?

**Comment by stannls** [comment]
Im currently rewriting the flake file with naersk. The openssl and alsa-lib dependencies were copied from an old project and I forgot to remove them.

**Comment by DaniD3v** [comment]
pkg-config isn't a dependency either btw. I just checked.
